name = "bitswap"

[builders]
  "docker:go" = { enabled = true, enable_go_build_cache = true }

[runners]
  "local:docker" = { enabled = true }
  "cluster:k8s" = { enabled = true }

[global.build_config]
  enable_go_build_cache = true

[[testcases]]
  name = "speed-test"
  instances = { min = 2, max = 100, default = 2 }

  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
  latencies = { type = "string", desc = "latencies to try with; comma-separated list of durations", default = '["100ms", "200ms", "300ms"]' }
  bandwidths = { type = "string", desc = "bandwidths (egress bytes/s) to try with; comma-separated list of humanized sizes", default = '["10M", "1M", "512kb"]' }
